version: '3'

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TUNNEL_TOKEN}
    container_name: cloudflared
    networks:
      - cloudflared
    restart: always

  bitwarden:
    image: vaultwarden/server
    container_name: bitwarden
    depends_on:
      - cloudflared
    environment:
      SIGNUPS_ALLOWED: 'false'   # set to false to disable signups
      WEBSOCKET_ENABLED: 'true'
      ADMIN_TOKEN: ${BW_ADMIN_TOKEN}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_FROM: ${SMTP_USER}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SSL: 'true'
      SMTP_USERNAME: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASS}
      YUBICO_CLIENT_ID: ${BW_YUBICO_CLIENT_ID}
      YUBICO_SECRET_KEY: ${BW_YUBICO_SECRET_KEY}
    networks:
      - cloudflared
    restart: always
    volumes:
      - bitwarden-data:/data

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - TZ=${TZ}
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=${SMTP_USER}
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=${WATCHTOWER_NOTIFICATION_EMAIL_TO}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=${SMTP_HOST}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=${SMTP_PORT}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=${SMTP_USER}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=${SMTP_PASS}
      - WATCHTOWER_SCHEDULE=${WATCHTOWER_SCHEDULE}
    hostname: gcp-bitwarden
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  backups:
    image: ghcr.io/krimil/bitwarden_rs-local-backup:main
    container_name: backups
    environment:
      - BACKUP_DAYS
      - BACKUP_RCLONE_DEST
      - BACKUP_ENCRYPTION_KEY
    restart: always
    volumes:
      - bitwarden-data:/data
      - $HOME/rclone:/config
      - $HOME/backups:/backups

networks:
  cloudflared:

volumes:
  bitwarden-data:
    driver_opts:
      type: none
      o: bind
      device: $HOME/docker/bitwarden/data
